name: Tectonic
description: Build TeX/LaTeX documents with Tectonic
inputs:
  src:
    description: The directory to recursively find TeX documents in
    required: true
  target:
    description: The directory to put generated files
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.src }}
    - ${{ inputs.target }}