name: MikTeX
description: MixTeX in GitHub Actions
inputs:
  documents:
    description: The TeX documents to operate on
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.documents }}